spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:weatherdb
  h2:
    console:
      enabled: true
  config:
    import: optional:file:.env[.properties]

weather-stack:
  access-key: ${ACCESS_KEY:default}

resilience4j:
  ratelimiter:
    instances:
      user-rate-limit:
        limitForPeriod: 10
        limitRefreshPeriod: 1m
        timeoutDuration: 10s